# Generated by Django 5.0.4 on 2024-05-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='filename',
            field=models.CharField(max_length=100000),
        ),
        migrations.AlterField(
            model_name='data',
            name='parent_id',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='data',
            name='text',
            field=models.CharField(max_length=1000000),
        ),
    ]
